### ISSUE TITLE
Text menu tolbar disappears when text is long

### ISSUE THREAD

**Issue by dawid-g** [antaresproject/notifications#11]
Go to: /admin/notifications/create

Before: https://image.prntscr.com/image/R5PlAHdGQ-21T8hf2Cu7qQ.png

After pasted very long text:  https://image.prntscr.com/image/V8vHMfxpQYyQ0HiGoZACvQ.png

Results:

Text menu tolbar disappears when text is long

**Comment by MarcinKozak** [comment]
@dawid-g Fixed

**Comment by dawid-g** [comment]
Potwierdzam, zamykam.
