### ISSUE TITLE
Template Content - More lines for HTML form

### ISSUE THREAD

**Issue by dawid-g** [antaresproject/notifications#12]
Go to: /admin/notifications/create

Results:

https://image.prntscr.com/image/gnlAjmhIQOWQNrpQhq6I0w.png

Template Content -  the html form sould have more lines by default, now it's only one line

**Comment by MarcinKozak** [comment]
@dawid-g Fixed

**Comment by dawid-g** [comment]
Potwierdzam, zamykam.
