### ISSUE TITLE
ErrorException when creating template without selected recipient

### ISSUE THREAD

**Issue by dawid-g** [antaresproject/notifications#14]
1. Go to: /admin/notifications/create
2. Enter valid data to all field besides "Recipienst"
3. Click "Submit" 

Results:
https://image.prntscr.com/image/vjynepR5RyK6WM_hSW2AUw.png

**Comment by MarcinKozak** [comment]
@dawid-g fixed

**Comment by dawid-g** [comment]
confirmed.
