### ISSUE TITLE
Empty required fields - lack error validations

### ISSUE THREAD

**Issue by dawid-g** [antaresproject/notifications#15]
1. Go to: /admin/notifications
2. Leave all fields empty and click submit

Results:
Error validation isn't displayed 

![valivalidation](https://user-images.githubusercontent.com/26220123/33270558-c57363d6-d384-11e7-924c-369fa41bbc5b.gif)

**Comment by MarcinKozak** [comment]
@dawid-g fixed

**Comment by dawid-g** [comment]
confirmed.
