### ISSUE TITLE
Notifications - incorrect content of messages

### ISSUE THREAD

**Issue by dawid-g** [antaresproject/notifications#16]
1. Send preview of this template: admin/notifications/2/edit
2. Check mailbox

Results:

Template has tekst: "testtekstTEKST"

Email message which is coming to my mailbox: https://image.prntscr.com/image/5N83lKh9TS6VEkzTHMNtsw.png

**Comment by MarcinKozak** [comment]
@dawid-g fixed

**Comment by dawid-g** [comment]
verified as fixed.
