### ISSUE TITLE
Formatting text cases

### ISSUE THREAD

**Issue by dawid-g** [antaresproject/notifications#18]
1. I wrote tekst with indentations in template tekst area
2. Send message, or see preview 

Results:
There is no indentations in mail message, or preview 

https://image.prntscr.com/image/jZyFNurWSA2TnVd3ir1pfA.png

**Comment by MarcinKozak** [comment]
@dawid-g fixed

**Comment by dawid-g** [comment]
Similar issue:

I have templates with is looks like this: admin/notifications/16/edit  (look at font and tables)

And after sending it looks like this:  https://image.prntscr.com/image/kG0AVZnyRs_kse85pPI-eA.png
