### ISSUE TITLE
Email Branding - lack of added variables

### ISSUE THREAD

**Issue by dawid-g** [antaresproject/notifications#21]
1. I have added [[ foundation::user.firstname ]] to Title section in email brand (/admin/branding/email)
2. I was sending random email notification

Results:

Lack of  user firstname in mail title:
https://image.prntscr.com/image/Ep0k-dSdQs6cib53qUGfMA.png

**Comment by dawid-g** [comment]
Another test, and incorrectly display:

/admin/branding/email
https://image.prntscr.com/image/XpPzM3R5QkuOgGMmjBPK4A.png

**Comment by dawid-g** [comment]
@mountstone can You verify this?

**Comment by mountstone** [comment]
@MarcinKozak 

1. edit notification page has problems with loading:

![2](https://user-images.githubusercontent.com/6020063/33431012-fac59b8a-d5d2-11e7-9e34-63f4e6076069.PNG)


It is problem with code of javascript.

2.  Template variable is missing:

![3](https://user-images.githubusercontent.com/6020063/33430952-ae76ce70-d5d2-11e7-9251-62eb1cf4e20c.PNG)


3. Template variables is missing on branding page:

![1](https://user-images.githubusercontent.com/6020063/33430978-c6bf511e-d5d2-11e7-97cb-a9c38eedc4ec.PNG)

**Comment by MarcinKozak** [comment]
@dawid-g @mountstone Fixed all 3 points.

**Comment by dawid-g** [comment]
verified as fixed.
