### ISSUE TITLE
The counter of unread actions is restarted after a page refresh

### ISSUE THREAD

**Issue by dawid-g** [antaresproject/notifications#22]
1. Generate some alerts or notifications on sidebars
2. Read it - counter shows "0"
3. Refresh the page

Results:
The counter of unread actions is restarted, it shows again the number of notifications, should be 0

https://image.prntscr.com/image/0vOrbwqZR4yRCuar869CjQ.png

**Comment by MarcinKozak** [comment]
@dawid-g Fixed

**Comment by dawid-g** [comment]
verified as fixed.
