### ISSUE TITLE
Filter - "User"

### ISSUE THREAD

**Issue by dawid-g** [antaresproject/notifications#24]
1. Go to:  admin/notifications
2. Select filter by "User" 

Results: 
Empty list, the notification does not have User recipient, should be "Client" and it should lists notifications assigned to "Client" recipients.

EDIT. Filter by status or category doesn't work to.

**Comment by MarcinKozak** [comment]
@dawid-g Filters for single value are fixed. Described by you filter does not affect to recipient.

**Comment by dawid-g** [comment]
Ok, Closed.
