### ISSUE TITLE
Notification -> mail messages content - two cases

### ISSUE THREAD

**Issue by dawid-g** [antaresproject/notifications#27]
1:
Mail content which is sent by notification, is displayed under the email brand staff: https://image.prntscr.com/image/7ItPHuk9QxiUxWUsECcJiQ.png

2:
I have templates with many variables (admin/notifications/18/edit), but there is only data and time in mail message displayed: 
https://image.prntscr.com/image/7ItPHuk9QxiUxWUsECcJiQ.png

**Comment by MarcinKozak** [comment]
@dawid-g 
Not correct only for brand and user variables. Rest of them are contextual so it will be empty. Fix in progress.

**Comment by dawid-g** [comment]
verified as fixed.
