### ISSUE TITLE
"field is required." error, when no such field exists

### ISSUE THREAD

**Issue by dawid-g** [antaresproject/notifications#9]
1. Go to /admin/notifications/create
2. Enter valid data, to all required fields
3. Click 'Save"

Actual results:

https://image.prntscr.com/image/F2qunO_dQRW8Fvptg34Yng.png  - but there is no "Severity ID" field in this form

**Comment by MarcinKozak** [comment]
@dawid-g Fixed

**Comment by dawid-g** [comment]
@MarcinKozak problem still persists.

**Comment by MarcinKozak** [comment]
@dawid-g Fixed

**Comment by dawid-g** [comment]
Despite that I have selected Event Category, there is displayed error message during Submit clicking:

https://image.prntscr.com/image/ysm4wn1xRgeu90QRKVpEUg.png

**Comment by dawid-g** [comment]
Update: after clicking on the Submit  https://image.prntscr.com/image/gPLnG2AbRJmVBInaDjrn-g.png

**Comment by MarcinKozak** [comment]
@dawid-g fixed for last updates of project, core and notifications module.

**Comment by dawid-g** [comment]
confirmed.
